# Make document when commit is pushed to main branch
name: Doxygen

on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: your-aws-region
          role-to-assume:  ${{ secrets.YOUR_ARN_FOR_DOXYGEN_ROLE }}
          role-session-name: PublishDocsWithDoxygen

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull image
        id: pull_image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: YOUR_ECR_REPOSITORY_NAME
          IMAGE_NAME:  $ECR_REGISTRY/$ECR_REPOSITORY:latest
        run: |
          docker pull ${{ env.IMAGE_NAME }}
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
          
      - name: Build document
        run: |
          cd ..
          mv your-repo-name/doxygen/repo_logo.png .
          mv your-repo-name/doxygen/Doxyfile .
          docker run --rm -v $(pwd):/workspace/data --workdir /workspace/data \
          ${{ steps.pull_image.outputs.IMAGE_NAME }} doxygen

      - name: Push document  
        run: |
          cd ..
          aws s3 sync --delete --region ap-northeast-1 ./html s3://your-repo-document/
